services:
  - type: web
    name: davinci-otio-beat-cutter
    env: python
    pythonVersion: 3.11.8
    buildCommand: python -m pip install -U pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
